name: pytest

on:
    push:

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - '3.11.5'
        name: test_run
        runs-on: ${{ matrix.os }}
