name: pytest_wf

on: [push]

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - '3.11.5'
        name: test_run
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code (build)
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies (from api folder)
              run: |
                  cd ./5_6_API
                  pip install -r requirements.txt

            - name: check model folder
              run: |
                  cd ./5_6_API/model
                  ls -lhR

            - name: get hash
              run: git lfs ls-files # 4021c2540f

            - name: check large object folder
              run: |
                  git lfs fetch --all
                  ls -lhR .git/lfs/objects
                  cp .git/lfs/objects/40/21/4021c2540f4e5c959a65ebc3b288223d5c60efc8e05ddd4e2f4f6de97f78434c ./5_6_API/model/pickled_knn.pkl

            - name: check knn size after fetching + copy
              run: ls -lhR ./5_6_API/model

            - name: Run tests
              run: |
                  cd ./5_6_API
                  pytest

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              working-directory: ./5_6_API
              with:
                  server: ftp.kaes5648.odns.fr
                  username: github@kaes5648.odns.fr
                  password: ${{ secrets.password_ftp }}
                  source: app.py # supprimer pour deploiement total, modifier ou ajouter au besoin.
                  target: /
