name: pytest_wf

on: [push]

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - '3.11.5'
        name: test_run
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies (from api folder)
              run: |
                  cd ./5_6_API
                  pip install -r requirements.txt

            - name: fetch large object (knn)
              run: git lfs fetch --all
              # git lfs fetch origin main

            - name: List fetched large object(s)
              run: ls -la .git/lfs/objects

            - name: Navigate into the directory containing the large object file
              run: |
                  cd .git/lfs/objects/40/21
                  ls -la

            - name: copy knn to subfolder
              run: mv .git/lfs/objects/pickled_knn.pkl 5_6_API/model/

            - name: Run tests
              run: |
                  cd ./5_6_API
                  pytest
