name: pytest_wf

on: [push]

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - '3.11.5'
        name: test_run
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies (from api folder)
              run: |
                  cd ./5_6_API
                  pip install -r requirements.txt

            - name: Find large file
              run: |
                  large_file_path=$(find . -name "pickled_knn.pkl" -type f)
                  cp "$large_file_path" 5_6_API/model/

            - name: Run tests
              run: |
                  cd ./5_6_API
                  pytest
